### PR TITLE
sql/parser, *: eschew a new FAMILIES keyword, extend STORING instead

### PR DESCRIPTION
**Pull request by knz**
There is an expressed need to enable multiple column families in
secondary indexes, so that a secondary index can later become a
suitable replacement for a PK.

The previous commit was moving in that direction by adding a dangling
new clause to index definitions, and also introducing a new keyword
for this purpose (FAMILIES).

This choice was introducing uncomfortable questions:

- what would it mean to express FAMILIES if there were no stored
  columns?
- is it the best UX to introduce syntax stuttering? (`FAMILIES(FAMILY FAMILY
  FAMILY)`)
- is it the best UX to have all the family definitions far away
  visually from the place where the stored columns are defined?
  (`STORING(a,b,c) FAMILIES(FAMILY a, FAMILY b, FAMILY c)`)
  After all the FAMILY clause is supported inside CREATE
  interleaved with column definitions, so each FAMILY
  can be defined "close to" the columns it contains.

This patch fixes this situation by acknowledging that the organization
of columns in families is a matter of data (storage) organization
and simply extends the STORING syntax to recognize family
definitions. For example:

```sql
CREATE INDEX b(x) STORING (y, FAMILY fy(y), z, FAMILY fz(z))
```

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
This was my first idea too, though @rohany pointed out that it's a bit misleading because it implies that you can only specify stored columns in families. In fact you can specify the key columns as well, though they all need to be in the first column family. So this should also be a valid statement:
```sql
CREATE INDEX b(x) STORING (y, FAMILY fxy(x, y), z, FAMILY fz(z))

```
But in the face of all the downsides you pointed out, I think I still prefer the STORING version.

**Comment by knz** [comment]
I think STORING should always accept the indexed columns and treat them as no-op.

Conversely I think the analysis of STORING should always consider the indexed columns as part of the stored set.

In other words the meaning of STORED is not "stored in the value part of the k/v pair" but instead more generally "stored in the index".

Once we shift the understanding in that direction, family definitions under STORING are completely well defined including for the indexed columns.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by solongordon** [comment]
Sounds good to me.

**Comment by knz** [comment]
btw PostgreSQL agrees with my understanding:

```
kena=> create table t(x int, y int);
CREATE TABLE
kena=> create index on t(x) include (x,y);
CREATE INDEX
```

**Comment by rohany** [comment]
alright, I'm going to merge this into my original PR.

**Comment by knz** [comment]
be sure to squash that merge commit in your branch

**Pull request merged**
